# Generated by Django 4.1.3 on 2022-12-04 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(help_text="Protocol to access the site e.g. 'http'", max_length=5)),
                ('domain', models.CharField(help_text="Site domain e.g. 'api.diary.com", max_length=255)),
                ('title', models.CharField(blank=True, default='Diary Api', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
    ]
