# Generated by Django 4.1.3 on 2022-12-04 19:28

import apps.users.models
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(db_index=True, error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 254 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=254, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='last name')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='birthday')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=apps.users.models.upload_handler, verbose_name='avatar')),
                ('is_active', models.BooleanField(default=True, verbose_name='is_active')),
                ('is_email_verified', models.BooleanField(default=False, verbose_name='is_email_verified')),
                ('is_notifications', models.BooleanField(default=True, verbose_name='is notifications')),
                ('gender', models.PositiveIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'None')], default=1)),
                ('age', models.CharField(blank=True, max_length=25, null=True)),
                ('last_password_changing', models.DateTimeField(blank=True, null=True, verbose_name='Last password changing')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff status')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='superuser status')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'users',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.users.models.UserManager()),
            ],
        ),
    ]
